### ISSUE TITLE
Is the client.html file in the wrong location?

### ISSUE THREAD

**Issue by ianjukes** [vppmatt/paymentgateway-standalone-17#1]
@vppmatt I think the `client.html` file is in the wrong place? I think it should be inside one of the static folders inside the `src/main/java/resources/` folder?

**Comment by vppmatt** [comment]
@ianjukes  The html file is standalone - it can just be opened directly in the browser (it doesn't need to be served by the running application). I put it in the root to make it easy to find but I'll put a copy into the resources/static folder as well so that it will work at http://localhost:8080/client.html.

**Comment by ianjukes** [comment]
Ah! We didn't think to try that. Of course. Thanks @vppmatt.
